### ISSUE TITLE
demo里面的几乎所有操作都会有问题

### ISSUE THREAD

**Issue by KingYoung87** [fesiong/sewise#1]
![image](https://cloud.githubusercontent.com/assets/9124243/23743682/966f463e-04ec-11e7-899b-3c28aca3f5e2.png)
请帮忙查看一下，谢谢

**Comment by fesiong** [comment]
不是吧？太可怜了

**Comment by KingYoung87** [comment]
这个问题已经解决了，哈哈。忘记关闭了～
