### ISSUE TITLE
关于音频类型与生成标签的问题

### ISSUE THREAD

**Issue by gto999** [fesiong/sewise#3]
如果现在类型为AUDIO，并且格式为M3U8，那问题来了，SEWISE直接创建成了VIDEO这种标签，在支持VIDEO的浏览器中，这就会导至一个问题，音频在微信端是全屏播的，因为是用VIDEO标签，不是用AUDIO标签，所以希望CONFIG里加一个类型，是VIDEO还是AUDIO来进行生成，我理解这样才是正确的生成方式。音频流现在也比较广泛，网络FM之类的，好多都是用M3U8格式，所以希望作者可以修复，如果没有时间，希望能公开JS源码，我可以帮你修复，多谢。

**Comment by fesiong** [comment]
https://github.com/sewise/sewise-player2
源码是这，不过好像不是最新版的，最新版他们没有公布

**Comment by XinJiangQingMang** [comment]
支持mp3吗

**Comment by fesiong** [comment]
mp3支持的
